webtalk_init -webtalk_dir C:/Users/student/Desktop/nimitt/22110169_22110203_LAB4/22110169_22110203_LAB4.sim/sim_1/behav/xsim/xsim.dir/ShiftRegister_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 31 10:37:53 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f27fa5d-085a-46d1-99dc-f7cc39e50e25" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "99d596b8c7704f4fb1bb21fb93b96ccd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7888_KB" -context "xsim\\usage"
webtalk_transmit -clientid 863172001 -regid "" -xml C:/Users/student/Desktop/nimitt/22110169_22110203_LAB4/22110169_22110203_LAB4.sim/sim_1/behav/xsim/xsim.dir/ShiftRegister_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/student/Desktop/nimitt/22110169_22110203_LAB4/22110169_22110203_LAB4.sim/sim_1/behav/xsim/xsim.dir/ShiftRegister_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/student/Desktop/nimitt/22110169_22110203_LAB4/22110169_22110203_LAB4.sim/sim_1/behav/xsim/xsim.dir/ShiftRegister_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
